disable ntfs for now due to
Today's linux-next build (powerpc allyesconfig) failed like this:

fs/ntfs/aops.c: In function 'ntfs_write_mst_block':
fs/ntfs/aops.c:1311:1: error: the frame size of 2304 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]
 1311 | }
      | ^

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>